In [3]:
import pandas as pd 
import numpy as np
import matplotlib
%matplotlib inline
import seaborn as sns 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')
import os

In [6]:
os.chdir("C:\\Users\\ACER\\Downloads\\Batch 75 Day15\\Batch 75 Day15\\")
data=pd.read_csv("pacific.csv")
print(data)

             ID                 Name      Date  Time Event Status Latitude  \
0      EP011949              UNNAMED  19490611     0           TS    20.2N   
1      EP011949              UNNAMED  19490611   600           TS    20.2N   
2      EP011949              UNNAMED  19490611  1200           TS    20.2N   
3      EP011949              UNNAMED  19490611  1800           TS    20.3N   
4      EP011949              UNNAMED  19490612     0           TS    20.4N   
...         ...                  ...       ...   ...   ...    ...      ...   
26132  EP222015               SANDRA  20151128  1200           LO    21.7N   
26133  EP222015               SANDRA  20151128  1800           LO    22.4N   
26134  EP222015               SANDRA  20151129     0           LO    23.1N   
26135  EP222015               SANDRA  20151129   600           LO    23.5N   
26136  EP222015               SANDRA  20151129  1200           LO    24.2N   

      Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind 

In [7]:
print (data.groupby('Status').agg({'Status': np.size}))

        Status
Status        
 DB        217
 ET        152
 EX        110
 HU       6766
 LO       1828
 PT          6
 SD          4
 SS          7
 ST          6
 TD       6965
 TS      10076


In [8]:
data.Status = pd.Categorical(data.Status)
data['Status'] = data.Status.cat.codes
display (data.head())

ID                 Name      Date  Time Event  Status Latitude  \
0  EP011949              UNNAMED  19490611     0            10    20.2N   
1  EP011949              UNNAMED  19490611   600            10    20.2N   
2  EP011949              UNNAMED  19490611  1200            10    20.2N   
3  EP011949              UNNAMED  19490611  1800            10    20.3N   
4  EP011949              UNNAMED  19490612     0            10    20.4N   

  Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  \
0    106.3W            45              -999  ...         -999         -999   
1    106.4W            45              -999  ...         -999         -999   
2    106.7W            45              -999  ...         -999         -999   
3    107.7W            45              -999  ...         -999         -999   
4    108.6W            45              -999  ...         -999         -999   

   Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  \
0              -999              -999              -999              -999   
1              -999              -999              -999              -999   
2              -999              -999              -999              -999   
3              -999              -999              -999              -999   
4              -999              -999              -999              -999   

   High Wind NE  High Wind SE  High Wind SW  High Wind NW  
0          -999          -999          -999          -999  
1          -999          -999          -999          -999  
2          -999          -999          -999          -999  
3          -999          -999          -999          -999  
4          -999          -999          -999          -999  

[5 rows x 22 columns]

In [9]:
print (data.groupby('Status').agg({'Status': np.size}))

        Status
Status        
0          217
1          152
2          110
3         6766
4         1828
5            6
6            4
7            7
8            6
9         6965
10       10076


In [10]:
pred_columns = data[:]
pred_columns.drop(['Status'],axis=1,inplace=True)
pred_columns.drop(['Event'],axis=1,inplace=True)
pred_columns.drop(['Latitude'],axis=1,inplace=True)
pred_columns.drop(['Longitude'],axis=1,inplace=True)
pred_columns.drop(['ID'],axis=1,inplace=True)
pred_columns.drop(['Name'],axis=1,inplace=True)
pred_columns.drop(['Date'],axis=1,inplace=True)
pred_columns.drop(['Time'],axis=1,inplace=True)
display((pred_columns))

Maximum Wind  Minimum Pressure  Low Wind NE  Low Wind SE  Low Wind SW  \
0                45              -999         -999         -999         -999   
1                45              -999         -999         -999         -999   
2                45              -999         -999         -999         -999   
3                45              -999         -999         -999         -999   
4                45              -999         -999         -999         -999   
...             ...               ...          ...          ...          ...   
26132            35              1002           60            0            0   
26133            30              1007            0            0            0   
26134            30              1008            0            0            0   
26135            25              1009            0            0            0   
26136            20              1010            0            0            0   

       Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  \
0             -999              -999              -999              -999   
1             -999              -999              -999              -999   
2             -999              -999              -999              -999   
3             -999              -999              -999              -999   
4             -999              -999              -999              -999   
...            ...               ...               ...               ...   
26132            0                 0                 0                 0   
26133            0                 0                 0                 0   
26134            0                 0                 0                 0   
26135            0                 0                 0                 0   
26136            0                 0                 0                 0   

       Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  \
0                  -999          -999          -999          -999   
1                  -999          -999          -999          -999   
2                  -999          -999          -999          -999   
3                  -999          -999          -999          -999   
4                  -999          -999          -999          -999   
...                 ...           ...           ...           ...   
26132                 0             0             0             0   
26133                 0             0             0             0   
26134                 0             0             0             0   
26135                 0             0             0             0   
26136                 0             0             0             0   

       High Wind NW  
0              -999  
1              -999  
2              -999  
3              -999  
4              -999  
...             ...  
26132             0  
26133             0  
26134             0  
26135             0  
26136             0  

[26137 rows x 14 columns]

In [11]:
x = pred_columns.values
display (x)

array([[  45, -999, -999, ..., -999, -999, -999],
       [  45, -999, -999, ..., -999, -999, -999],
       [  45, -999, -999, ..., -999, -999, -999],
       ...,
       [  30, 1008,    0, ...,    0,    0,    0],
       [  25, 1009,    0, ...,    0,    0,    0],
       [  20, 1010,    0, ...,    0,    0,    0]], dtype=int64)

In [12]:
y =data['Status'].values
print (y)

[10 10 10 ...  4  4  4]


In [13]:
from sklearn.model_selection  import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)
print (x.shape)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(26137, 14)
(18295, 14)
(7842, 14)
(18295,)
(7842,)


In [14]:
x

array([[  45, -999, -999, ..., -999, -999, -999],
       [  45, -999, -999, ..., -999, -999, -999],
       [  45, -999, -999, ..., -999, -999, -999],
       ...,
       [  30, 1008,    0, ...,    0,    0,    0],
       [  25, 1009,    0, ...,    0,    0,    0],
       [  20, 1010,    0, ...,    0,    0,    0]], dtype=int64)

In [15]:
y

array([10, 10, 10, ...,  4,  4,  4], dtype=int8)

In [16]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
log_pred = logmodel.predict(x)
print (log_pred)
print (pd.DataFrame(log_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,log_pred))
print('\nClassification Report')
print(classification_report (y,log_pred))
print('Confusion Matrix')
print (confusion_matrix (y,log_pred))

[10 10 10 ...  4  4  4]
        0
0        
3    6913
4    3019
9    5212
10  10993

 Accuracy Score
0.7772506408539618

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.85      0.87      0.86      6766
           4       0.55      0.91      0.69      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.82      0.62      0.71      6965
          10       0.77      0.84      0.80     10076

    accuracy                           0.78     26137
   macro avg       0.27      0.29      0.28     26137
weighted avg       0.78      0.78      0.77     26137

Confusion Matrix
[[   0    0    0    0  217 

In [17]:
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier(n_neighbors =100 , metric = 'minkowski', p= 2)
KNN1.fit(x_train,y_train)
KNN1_pred = KNN1.predict(x)
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,KNN1_pred))
print('\nClassification Report')
print(classification_report (y,KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (y,KNN1_pred))

[10 10 10 ...  9  4  4]
        0
0        
3    6793
4    1966
9    7224
10  10154

 Accuracy Score
0.9507977197076941

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.99      0.99      6766
           4       0.74      0.79      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      0.99      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.33      0.34      0.34     26137
weighted avg       0.93      0.95      0.94     26137

Confusion Matrix
[[    0     0     0     0  

In [18]:
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier(n_neighbors =5 , metric = 'minkowski', p= 2)
KNN1.fit(x_train,y_train)
KNN1_pred = KNN1.predict(x)
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,KNN1_pred))
print('\nClassification Report')
print(classification_report (y,KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (y,KNN1_pred))

[10 10 10 ...  9  4  4]
        0
0        
0     170
2      13
3    6782
4    1669
7       1
9    7323
10  10179

 Accuracy Score
0.9499942610092972

Classification Report
              precision    recall  f1-score   support

           0       0.22      0.17      0.19       217
           1       0.00      0.00      0.00       152
           2       0.77      0.09      0.16       110
           3       1.00      1.00      1.00      6766
           4       0.75      0.69      0.72      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      1.00      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.42      0.36      0.36     26137
weighted avg       0.94      0.95      0.94     26137

Confusion Matr

In [19]:
KNN1_pred = KNN1.predict(x_test)
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (y_test,KNN1_pred))
print('\nClassification Report')
print(classification_report (y_test,KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (y_test,KNN1_pred))

[10  9  3 ...  4  9  9]
       0
0       
0     50
2      4
3   2009
4    518
9   2172
10  3089

 Accuracy Score
0.949885233358837

Classification Report
              precision    recall  f1-score   support

           0       0.18      0.12      0.14        76
           1       0.00      0.00      0.00        47
           2       0.50      0.06      0.11        32
           3       1.00      1.00      1.00      2000
           4       0.72      0.71      0.72       522
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         4
           9       0.92      0.96      0.94      2095
          10       0.99      1.00      1.00      3062

    accuracy                           0.95      7842
   macro avg       0.39      0.35      0.35      7842
weighted avg       0.94      0.95      0.94      7842

Confusion Matrix
[[   9    0    0

In [20]:
from sklearn.neighbors import KNeighborsClassifier
KNN2 = KNeighborsClassifier(n_neighbors =100 , metric = 'minkowski', p= 1)
KNN2.fit(x_train,y_train)
KNN2_pred = KNN2.predict(x)
print (KNN2_pred)
print (pd.DataFrame(KNN2_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,KNN2_pred))
print('\nClassification Report')
print(classification_report (y,KNN2_pred))
print('Confusion Matrix')
print (confusion_matrix (y,KNN2_pred))

[10 10 10 ...  9  4  4]
        0
0        
3    6771
4    1956
9    7253
10  10157

 Accuracy Score
0.9520602976623178

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.99      0.99      6766
           4       0.74      0.79      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      1.00      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.33      0.34      0.34     26137
weighted avg       0.94      0.95      0.94     26137

Confusion Matrix
[[    0     0     0     0  

In [21]:
KNN2_pred = KNN2.predict(x_test)
print (KNN2_pred)
print (pd.DataFrame(KNN2_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y_test,KNN2_pred))
print('\nClassification Report')
print(classification_report (y_test,KNN2_pred))
print('Confusion Matrix')
print (confusion_matrix (y_test,KNN2_pred))

[10  9  3 ...  4  9  9]
       0
0       
3   2006
4    597
9   2163
10  3076

 Accuracy Score
0.9521805661820965

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        76
           1       0.00      0.00      0.00        47
           2       0.00      0.00      0.00        32
           3       0.99      1.00      1.00      2000
           4       0.72      0.82      0.76       522
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         4
           9       0.93      0.96      0.94      2095
          10       0.99      0.99      0.99      3062

    accuracy                           0.95      7842
   macro avg       0.33      0.34      0.34      7842
weighted avg       0.93      0.95      0.94      7842

Confusion Matrix
[[   0    0    0    0   73    0  

In [22]:
from sklearn.naive_bayes import GaussianNB
GNB= GaussianNB()
GNB.fit(x_train,y_train)
GNB_pred = GNB.predict(x)
print (GNB_pred)
print (pd.DataFrame(GNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,GNB_pred))
print('\nClassification Report')
print(classification_report (y,GNB_pred))
print('Confusion Matrix')
print (confusion_matrix (y,GNB_pred))

[1 1 1 ... 0 0 0]
        0
0        
0    2714
1   19749
3    1236
4      10
5     233
6     304
7    1859
8      18
10     14

 Accuracy Score
0.06244021884684547

Classification Report
              precision    recall  f1-score   support

           0       0.08      0.99      0.15       217
           1       0.01      1.00      0.02       152
           2       0.00      0.00      0.00       110
           3       1.00      0.18      0.31      6766
           4       0.00      0.00      0.00      1828
           5       0.01      0.33      0.02         6
           6       0.01      1.00      0.03         4
           7       0.00      1.00      0.01         7
           8       0.28      0.83      0.42         6
           9       0.00      0.00      0.00      6965
          10       1.00      0.00      0.00     10076

    accuracy                           0.06     26137
   macro avg       0.22      0.49      0.09     26137
weighted avg       0.64      0.06      0.08     26137


In [23]:
from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(x_train,y_train)
BNB_pred = BNB.predict(x)
print (BNB_pred)
print (pd.DataFrame(BNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,BNB_pred))
print('\nClassification Report')
print(classification_report (y,BNB_pred))
print('Confusion Matrix')
print (confusion_matrix (y,BNB_pred))

[9 9 9 ... 9 9 9]
        0
0        
3      18
7     685
8    1212
9   22770
10   1452

 Accuracy Score
0.3204269809082909

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.00      0.00      0.00      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.29      0.01         7
           8       0.00      1.00      0.01         6
           9       0.31      1.00      0.47      6965
          10       0.97      0.14      0.24     10076

    accuracy                           0.32     26137
   macro avg       0.12      0.22      0.07     26137
weighted avg       0.45      0.32      0.22     26137

Confusion Matrix
[[   0    0    0    0  

In [24]:
from sklearn.preprocessing import MinMaxScaler
MMS = MinMaxScaler()
MMS_train_x = MMS.fit_transform(x_train)
MMS_train_y = y_train 

from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(MMS_train_x,MMS_train_y)
MMS_data = MMS.fit_transform (x)
MNB_pred = MNB.predict(MMS_data )
print (MNB_pred)
print (pd.DataFrame(MNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,MNB_pred))
print('\nClassification Report')
print(classification_report (y,MNB_pred))
print('Confusion Matrix')
print (confusion_matrix (y,MNB_pred))

[10 10 10 ... 10 10 10]
        0
0        
3     801
10  25336

 Accuracy Score
0.41615334583157976

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       1.00      0.12      0.21      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.00      0.00      0.00      6965
          10       0.40      1.00      0.57     10076

    accuracy                           0.42     26137
   macro avg       0.13      0.10      0.07     26137
weighted avg       0.41      0.42      0.27     26137

Confusion Matrix
[[    0     0     0     0     0     0     0   

In [25]:
from sklearn.svm import SVC
SVM_SIG = SVC (kernel = 'linear')
SVM_SIG.fit(x_train,y_train)
SVM_SIG_pred = SVM_SIG.predict(x)
print (SVM_SIG_pred)
print (pd.DataFrame(SVM_SIG_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,SVM_SIG_pred))
print('\nClassification Report')
print(classification_report (y,SVM_SIG_pred))
print('Confusion Matrix')
print (confusion_matrix (y,SVM_SIG_pred))

[10 10 10 ...  9  4  4]
        0
0        
0       1
2       1
3    6784
4    2150
7       2
8       7
9    7023
10  10169

 Accuracy Score
0.9543176340054329

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       1.00      0.01      0.02       110
           3       1.00      1.00      1.00      6766
           4       0.71      0.83      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       1.00      0.29      0.44         7
           8       0.57      0.67      0.62         6
           9       0.94      0.94      0.94      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.95     26137
   macro avg       0.56      0.43      0.43     26137
weighted avg       0.94      0.95      0.95     26137

Conf

In [26]:
from sklearn.svm import SVC
SVM_SIG = SVC (kernel = 'poly')
SVM_SIG.fit(x_train,y_train)
SVM_SIG_pred = SVM_SIG.predict(x)
print (SVM_SIG_pred)
print (pd.DataFrame(SVM_SIG_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,SVM_SIG_pred))
print('\nClassification Report')
print(classification_report (y,SVM_SIG_pred))
print('Confusion Matrix')
print (confusion_matrix (y,SVM_SIG_pred))

[10 10 10 ... 10 10 10]
        0
0        
3    5643
9    7556
10  12938

 Accuracy Score
0.7708612312048054

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       1.00      0.83      0.91      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.77      0.84      0.81      6965
          10       0.67      0.86      0.75     10076

    accuracy                           0.77     26137
   macro avg       0.22      0.23      0.22     26137
weighted avg       0.72      0.77      0.74     26137

Confusion Matrix
[[   0    0    0    0    0    0    0 

In [27]:
from sklearn.svm import SVC
SVM_SIG = SVC (kernel = 'rbf')
SVM_SIG.fit(x_train,y_train)
SVM_SIG_pred = SVM_SIG.predict(x)
print (SVM_SIG_pred)
print (pd.DataFrame(SVM_SIG_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,SVM_SIG_pred))
print('\nClassification Report')
print(classification_report (y,SVM_SIG_pred))
print('Confusion Matrix')
print (confusion_matrix (y,SVM_SIG_pred))

[10 10 10 ...  4  4  4]
        0
0        
3    5328
4    3257
10  17552

 Accuracy Score
0.6408922217546008

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.78      0.87      6766
           4       0.51      0.92      0.66      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.00      0.00      0.00      6965
          10       0.56      0.97      0.71     10076

    accuracy                           0.64     26137
   macro avg       0.19      0.24      0.20     26137
weighted avg       0.51      0.64      0.55     26137

Confusion Matrix
[[   0    0    0    0  217    0    0 

In [28]:
from sklearn.tree import DecisionTreeClassifier
SVM_SIG = DecisionTreeClassifier()
SVM_SIG.fit(x_train,y_train)
SVM_SIG_pred = SVM_SIG.predict(x)
print (SVM_SIG_pred)
print (pd.DataFrame(SVM_SIG_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,SVM_SIG_pred))
print('\nClassification Report')
print(classification_report (y,SVM_SIG_pred))
print('Confusion Matrix')
print (confusion_matrix (y,SVM_SIG_pred))

[10 10 10 ...  9  4  4]
        0
0        
2      24
3    6783
4    2086
5       3
7      10
8       7
9    7106
10  10118

 Accuracy Score
0.9587175268776065

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.88      0.19      0.31       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       0.67      0.33      0.44         6
           6       0.00      0.00      0.00         4
           7       0.70      1.00      0.82         7
           8       0.57      0.67      0.62         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.59      0.54      0.54     26137
weighted avg       0.95      0.96      0.95     26137

Conf

In [29]:
from sklearn.tree import DecisionTreeClassifier
TREE = DecisionTreeClassifier (criterion = 'entropy')
TREE.fit(x_train,y_train)
TREE_pred = TREE.predict(x)
print (TREE_pred)
print (pd.DataFrame(TREE_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,TREE_pred))
print('\nClassification Report')
print(classification_report (y,TREE_pred))
print('Confusion Matrix')
print (confusion_matrix (y,TREE_pred))


[10 10 10 ...  9  4  4]
        0
0        
2      24
3    6784
4    2087
5       2
7       9
8       6
9    7106
10  10119

 Accuracy Score
0.9588705666296821

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.88      0.19      0.31       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.78      1.00      0.88         7
           8       0.83      0.83      0.83         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.65      0.56      0.57     26137
weighted avg       0.95      0.96      0.95     26137

Conf

In [30]:
from sklearn.tree import DecisionTreeClassifier
TREE_GINI = DecisionTreeClassifier (criterion = 'gini')
TREE_GINI.fit(x_train,y_train)
TREE_GINI_pred = TREE_GINI.predict(x)
print (TREE_GINI_pred)
print (pd.DataFrame(TREE_GINI_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,TREE_GINI_pred))
print('\nClassification Report')
print(classification_report (y,TREE_GINI_pred))
print('Confusion Matrix')
print (confusion_matrix (y,TREE_GINI_pred))

[10 10 10 ...  9  4  4]
        0
0        
2      24
3    6783
4    2090
5       3
7      10
8       7
9    7106
10  10114

 Accuracy Score
0.9586410070015686

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.88      0.19      0.31       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       0.67      0.33      0.44         6
           6       0.00      0.00      0.00         4
           7       0.70      1.00      0.82         7
           8       0.57      0.67      0.62         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.59      0.54      0.54     26137
weighted avg       0.95      0.96      0.95     26137

Conf

In [31]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100, criterion='entropy')
RF.fit(x_train,y_train)
RF_pred = RF.predict(x)
print (RF_pred)
print (pd.DataFrame(RF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,RF_pred))
print('\nClassification Report')
print(classification_report (y,RF_pred))
print('Confusion Matrix')
print (confusion_matrix (y,RF_pred))

[10 10 10 ...  9  4  4]
        0
0        
2      25
3    6786
4    2071
5       2
7       6
8       4
9    7106
10  10137

 Accuracy Score
0.9591001262577955

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.84      0.19      0.31       110
           3       1.00      1.00      1.00      6766
           4       0.75      0.84      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       1.00      0.86      0.92         7
           8       1.00      0.67      0.80         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.68      0.53      0.57     26137
weighted avg       0.95      0.96      0.95     26137

Conf

In [32]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100, criterion='gini')
RF.fit(x_train,y_train)
RF_pred = RF.predict(x)
print (RF_pred)
print (pd.DataFrame(RF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,RF_pred))
print('\nClassification Report')
print(classification_report (y,RF_pred))
print('Confusion Matrix')
print (confusion_matrix (y,RF_pred))


[10 10 10 ...  9  4  4]
        0
0        
2      25
3    6786
4    2076
5       2
7       6
8       4
9    7106
10  10132

 Accuracy Score
0.9590618663197765

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.84      0.19      0.31       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       1.00      0.86      0.92         7
           8       1.00      0.67      0.80         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.68      0.53      0.57     26137
weighted avg       0.95      0.96      0.95     26137

Conf